name: elen4904
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - jupyter
  - pyarrow=14.0.2
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - yfinance
      - pandas-datareader
      - gymnasium
      - xgboost
